global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'basic-setup'
    static_configs:
      - targets: ['basic-setup:2112']
    metrics_path: '/metrics'

  - job_name: 'super-worker'
    static_configs:
      - targets: ['super-worker:2112']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

